version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: recipe_postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: recipe_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: recipe_backend
    environment:
      DB_HOST: postgres
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: recipe_app
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: recipe_frontend
    environment:
      VUE_APP_API_URL: http://recipe_backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
